apiVersion: apps/v1
kind: Deployment
metadata:
  name: dt-1
spec:
  selector:
    matchLabels:
      app: dt-1
  template:
    metadata:
      labels:
        app: dt-1
    spec:
      containers:
      - name: dt-1
        image: rssgai/dt-flask:mirroring-v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  name: dt-1-service
spec:
  selector:
    app: dt-1
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    nodePort: 30090
  type: NodePort
